# Generated by Django 4.0 on 2023-03-19 05:55

import Courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'CYBER SECURITY'), ('2', 'ETHICAL HACKING'), ('3', 'FORENSICS'), ('4', 'SOFTWARE DEV'), ('5', 'WELFARE')], max_length=25)),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to=Courses.models.Media)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField(max_length=1200)),
                ('file', models.FileField(upload_to='Media/uploads')),
            ],
        ),
    ]
