# Generated by Django 4.0 on 2023-03-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='file',
        ),
    ]
